name: Deploy Django & Snake CI/CD

on:
  push:
    branches:
      - main

env:
  DJANGO_IMAGE: rahmashelbayeh/djangoapp
  SNAKE_IMAGE: rahmashelbayeh/snakegame
  TAG: ${{ github.run_id }}

jobs:
  build_and_package:
    name: Build and Package Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python & build tools
        run: |
          sudo apt update
          sudo apt install -y python3 python3-venv python3-pip build-essential

      - name: Install Django dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r book-shop/requirements.txt

      - name: Package Django
        run: |
          mkdir -p artifacts
          tar -czf artifacts/django-app.tgz -C . book-shop

      - name: Package Snake
        run: |
          mkdir -p artifacts
          tar -czf artifacts/snake-app.tgz -C . snake

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-packages
          path: artifacts/

  docker_build_and_push:
    name: Build & Push Docker Images
    needs: build_and_package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Django
        uses: docker/build-push-action@v5
        with:
          context: ./book-shop
          file: ./book-shop/Dockerfile
          push: true
          tags: ${{ env.DJANGO_IMAGE }}:${{ env.TAG }}

      - name: Build & Push Snake
        uses: docker/build-push-action@v5
        with:
          context: ./snake
          file: ./snake/Dockerfile
          push: true
          tags: ${{ env.SNAKE_IMAGE }}:${{ env.TAG }}

  deploy:
    name: Deploy Apps on Blue VM
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # --- Stop old containers if exist ---
            docker rm -f djangoapp || true
            docker rm -f snakegame || true

            # --- Pull latest images ---
            docker pull ${{ env.DJANGO_IMAGE }}:${{ env.TAG }}
            docker pull ${{ env.SNAKE_IMAGE }}:${{ env.TAG }}

            # --- Run Django on port 80 ---
            docker run -d -p 80:8000 --name djangoapp ${{ env.DJANGO_IMAGE }}:${{ env.TAG }}

            # --- Run Snake on port 8080 ---
            docker run -d -p 8080:80 --name snakegame ${{ env.SNAKE_IMAGE }}:${{ env.TAG }}
