name: SnakeGame CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: rahmashelbayeh/snakegame
  TAG: ${{ github.run_id }}

jobs:
  build_app:
    name: Build and Package Snake Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Package static files
        run: |
          mkdir -p artifacts
          tar -czf artifacts/snake.tgz -C . .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-package
          path: artifacts/snake.tgz

  docker_build:
    name: Build and Push Docker Image
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    name: Deploy on VPS
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Stopping old Snake container if running..."
            docker rm -f snakegame || true
            echo "Pulling latest image..."
            docker pull ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            echo "Starting new Snake container..."
            docker run -d -p 80:80 --name snakegame ${{ env.IMAGE_NAME }}:${{ env.TAG }}
