name: Snake Game CI/CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: rahmashelbayeh/snakegame
  TAG: ${{ github.run_id }}

jobs:
  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./snakegame
          file: ./snakegame/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    name: Deploy on Server
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            #!/bin/bash

            IMAGE_NAME=${{ env.IMAGE_NAME }}:${{ env.TAG }}
            CONTAINER_NAME="snakegame"

            # حذف الحاوية القديمة إذا موجودة
            docker rm -f $CONTAINER_NAME 2>/dev/null || true

            # تشغيل الحاوية على البورت 80 → 8000
            docker run -d -p 80:8000 --name $CONTAINER_NAME $IMAGE_NAME

            echo "Snake game is running on port 80"
